sheets:
  form: https://docs.google.com/spreadsheets/d/18y1AOc-xN4ChmTi-7Aki5YoHoZEX0lbY-AkceMC985E/
  interviews: https://docs.google.com/spreadsheets/d/1rU0zxwcGzav12kOv50CHjd_QXDD1DP2rYNbbhfXIJZ4/
  old_automator: https://docs.google.com/spreadsheets/d/16cEyI66gi5si6MrYEsKqMrTnX5hJ2m8AEy1_1yYR40Q/

subsystem: "Sensing And Automation"
